// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/user_interface.go -destination=internal/service/user_interface_mock.go -package=service
//

// Package service is a generated GoMock package.
package service
